export const CONSTANTS = {
  SERVER_URL: 'https://api.didex.com/',
  MOCK_SERVER_URL: 'https://devapi.didex.com/',
  PHONE_VERIFICATION_CODE_LENGTH: 6,
  PAGINATION_LIMIT_BIG: 100,
  PAGINATION_LIMIT: 25,
  PAGINATION_LIMIT_SMALL: 10,
  RECAPTCHA_SITE_KEY: '6LcgguIUAAAAAE1GXYfJd7z-uEah67Dd9kTgWcpz',
  DEV_ACCESS_TOKEN:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNiIsImVtYWlsIjoibS5oYWRpLmphbXNoaWRpQGdtYWlsLmNvbSIsImp0aSI6ImM1MWRhYzNlLTVmOTctNDQ5NC05ODJiLTUzYjRmZTZmMzRhNCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMTYiLCJuYW1laWQiOiJuaWxvb2ZhciBqYW1zaGlkaSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InRyYWRlciIsImV4cCI6MTYyNTkyNzgzOSwiaXNzIjoiRGlkZXggQ29ycCIsImF1ZCI6IkRpZGV4IENvcnAifQ.6RCqPP0_Sypb4gVBTpHd7shNbsJQqaxSMwmYi8ptrsc',
};
