variables:
  RELEASE_FOLDER: 'dist'
  DEPLOY_FOLDER: 'c:\sites\didex.investClient'

stages:
  # - build
  # - test
  - deploy
  # - deliver

# build_job:
#   stage: build
#   only:
#     - tags
#   script:
#     - npm i
#     - ng build --prod
# test_job:
#   stage: test
#   only:
#     - tags
#   script:
#     - dir

deploy_job:
  stage: deploy
  only:
    - tags
  script:
    - npm i
    - npm run build-dev
    - xcopy  /S /Q /Y /F .\dist C:\sites\didex.investClient\
# deliver_job:
#   stage: deliver
#   only:
#     - tags
#   script:
#     - npm i
#     - npm run build
#     - xcopy  /S /Q /Y /F .\dist C:\sites-prod\didex.investClient\
# dependencies:
#   - build_job
#   - test_job
